name: Ansible Deployment

on:
  workflow_dispatch:
    inputs:
      approval:
        description: 'Approval to deploy'
        required: true
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Run Ansible Playbook
        run: ansible-playbook -i localhost, new.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
